services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/blocks_world
      - PORT=3000
    volumes:
      # Mount source code for development (hot reload)
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - bdi-network
    command: ["node", "server.js"]

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=blocks_world
    volumes:
      - mongo_data_dev:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    networks:
      - bdi-network

volumes:
  mongo_data_dev:

networks:
  bdi-network:
    driver: bridge