services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/blocks_world
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET:-dev-insecure-secret}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-dev-admin-password}
      - JWT_SECRET=please-change-me
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
    volumes:
      # Mount source code for development (hot reload)
      - ./backend:/app/backend
      - ./public:/app/public
      - /app/backend/node_modules
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - bdi-network
    command: ["node", "server.js"]

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=blocks_world
    volumes:
      - mongo_data_dev:/data/db
      - ./backend/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    networks:
      - bdi-network

volumes:
  mongo_data_dev:

networks:
  bdi-network:
    driver: bridge