services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: bdi-backend-dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - bdi-network
    restart: unless-stopped
    command: ["npm", "run", "dev"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bdi-frontend-dev
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - bdi-network
    restart: unless-stopped

networks:
  bdi-network:
    driver: bridge
